### ISSUE TITLE
插件启动报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [Alpaca4610/nonebot-plugin-audiocraft#2]
环境py3.9.12，nb2rc4

06-18 21:01:22 [ERROR] nonebot | Failed to import "nonebot_plugin_audiocraft"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\bot.py", line 31, in <module>
    nonebot.load_plugins("src/plugins")
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_audiocraft\__init__.py", line 11, in <module>
    __plugin_meta__ = PluginMetadata(
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by ElainaFanBoy** [comment]
草，把metadata全去掉就可以了（
