### ISSUE TITLE
触发指令报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [Alpaca4610/nonebot-plugin-audiocraft#3]
请问一下佬这个是怎么回事，触发生成指令后就报错了

Loaded as API: https://elainafanboy-musicgen.hf.space/ ✔
06-18 21:19:55 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_audiocraft) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_audiocraft\__init__.py", line 27, in _
    result = client.predict(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\gradio_client\client.py", line 263, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\gradio_client\client.py", line 943, in result
    return super().result(timeout=timeout)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\gradio_client\client.py", line 620, in _inner
    data = self.serialize(*data)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\gradio_client\client.py", line 753, in serialize
    assert len(data) == len(
AssertionError: Expected 0 arguments, got 8

**Comment by Alpaca4610** [comment]
你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可

**Comment by ElainaFanBoy** [comment]
> 你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可

用的抱脸的，虽然没报错了不过速度太慢了bot直接卡住了(

**Comment by Alpaca4610** [comment]
> > 你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可
> 
> 用的抱脸的，虽然没报错了不过速度太慢了bot直接卡住了(

可以把模型大小换成small，这样快一些

**Comment by ElainaFanBoy** [comment]
> > > 你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可
> > 
> > 
> > 用的抱脸的，虽然没报错了不过速度太慢了bot直接卡住了(
> 
> 可以把模型大小换成small，这样快一些

已经是small了，还是会卡一小会儿，是不是改成异步会好些

**Comment by Alpaca4610** [comment]
> > > > 你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可
> > > 
> > > 
> > > 用的抱脸的，虽然没报错了不过速度太慢了bot直接卡住了(
> > 
> > 
> > 可以把模型大小换成small，这样快一些
> 
> 已经是small了，还是会卡一小会儿，是不是改成异步会好些

已修改 但未测试

**Comment by ElainaFanBoy** [comment]
> > > > > 你用的是HF官方的部署环境吧，把代码第50行改成`fn_index=1`即可
> > > > 
> > > > 
> > > > 用的抱脸的，虽然没报错了不过速度太慢了bot直接卡住了(
> > > 
> > > 
> > > 可以把模型大小换成small，这样快一些
> > 
> > 
> > 已经是small了，还是会卡一小会儿，是不是改成异步会好些
> 
> 已修改 但未测试

辛苦了
